name: chat_box
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.14
  uuid: ^4.5.1
  intl: ^0.19.0
  flutter_slidable: ^3.1.1
  audioplayers: ^6.1.0
  file_picker: ^8.1.4
  image_picker: ^1.1.2
  waved_audio_player: ^1.2.1
  flutter_riverpod: ^2.6.1
  get_it: ^8.0.2
  ffmpeg_kit_flutter:
  path_provider: ^2.1.5

  flutter_facebook_auth: ^7.1.1
  google_sign_in: ^6.2.2
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  firebase_database: ^11.1.1
  cloud_firestore: ^5.4.5
  internet_connection_checker_plus: ^2.5.2
  dartz: ^0.10.1

  skeletonizer: ^1.4.2
  video_player: ^2.9.2
  chewie: ^1.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: null
  flutter_lints:

flutter_icons:
  android: true
  ios: false
  image_path: assets/icons/chatbox-icon.png
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/test/
  fonts:
    - family: Caros
      fonts:
        - asset: assets\fonts\font-caros.otf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
